language: java
jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install:
- mvn clean install 



deploy:
  provider: heroku
  api_key: ba99647a-7e9c-4c3d-b8bc-583e4e765a55
  app: cryptic-wave-85088